# Setup
title: 联合大会
tagline: 
url: https://vunconf.github.io
baseurl: ""
permalink: /:title/
timezone: Asia/Shanghai

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-147400618-6

# Specify the author for blog posts
author:
  name: 联合大会
  url: https://vunconf.github.io/
  email:

# Custom vars
version: 3.0.0

defaults:
  -
    scope:
      path: "iao"
    values:
      headtitle: "国际天文组织"
